let cityData = [
  {
    "id": 0,
    "address": "ул. Нариманова, 15Б",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
    "coords": [55.78568,49.103872],
  },
  {
    "id": 1,
    "address": "ул. Чистопольская, 33В",
    "workhour": "Круглосуточно",
    "workload": "Средняя загруженность",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "orange",
    "iconSrc": "img/icon-orange.png",
    "coords": [55.819853,49.12226],
  },
  {
    "id": 2,
    "address": "ул. Мусина, 61к1",
    "workhour": "Круглосуточно",
    "workload": "Сильная загруженность",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "red",
    "iconSrc": "img/icon-red.png",
    "coords": [55.833779,49.12164],
  },
  {
    "id": 3,
    "address": "ул. Гаврилова, 30",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
    "coords": [55.836969,49.158498],
  },
  {
    "id": 4,
    "address": "ул. Габдуллы Тукая, 115, корп. 5",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
    "coords": [55.766582,49.126887],
  },
  {
    "id": 5,
    "address": "ул. Аделя Кутуя, 86/7",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
    "coords": [55.781226,49.189104],
  }
];