let cityData = [
  {
    "id": 0,
    "address": "ул. Нариманова, 15Б",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
  },
  {
    "id": 1,
    "address": "ул. Чистопольская, 33В",
    "workhour": "Круглосуточно",
    "workload": "Средняя загруженность",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "orange",
    "iconSrc": "img/icon-orange.png",
  },
  {
    "id": 2,
    "address": "ул. Мусина, 61к1",
    "workhour": "Круглосуточно",
    "workload": "Сильная загруженность",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "red",
    "iconSrc": "img/icon-red.png",
  },
  {
    "id": 3,
    "address": "ул. Гаврилова, 30",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
  },
  {
    "id": 4,
    "address": "ул. Габдуллы Тукая, 115, корп. 5",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
  },
  {
    "id": 5,
    "address": "ул. Аделя Кутуя, 86/7",
    "workhour": "Круглосуточно",
    "workload": "Свободен",
    "imgSrc": "img/entry-address-img.jpg",
    "baloonColor": "green",
    "iconSrc": "img/icon-green.png",
  }
];